In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw = pd.read_excel('20190513_VN.xlsx', sheet_name = 'Sheet1')

In [4]:
rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
cols = np.arange(1, 13)

conditions = ['radicicol', 'DMSO']

samples = ['K298M', 'WT', 'Empty', 'W289H', 'T293D', 'G291L', 'T443K', 'F512A', 'F512P']
#samples = ['HSP1', 'HSP2', 'HSP3', 'HSP4', 'HSP5', 'HSP6', 'HSP7', 'HSP8' ,'HSP9']
wellsPerSample = 6
sampleCount = 9

colLabels = []
wellID = []
sampleLabels = []

row = 0
col = wellsPerSample
for idx in np.arange(9):
    if row > 7:
        row = row % 7 - 1
        col = col + 6
    colLabels = colLabels + [rows[row] + str(i) for i in np.arange(col - 5, col + 1)]
    row += 1
    
    sampleLabels = sampleLabels + [conditions[0] + '_' + str(idx) for num in np.arange(1, 4)]
    sampleLabels = sampleLabels + [conditions[1] + '_' + str(idx) for num in np.arange(1, 4)]

raw.rename(dict(zip(colLabels, sampleLabels)), axis = 1, inplace = True)

idx = ['_' not in name for name in raw.columns]
raw.drop(raw.columns[idx][2:], axis = 1, inplace = True)

raw['id'] = raw.index

In [14]:
raw

,Time,TÂ° Read 2:600,radicicol_0,radicicol_0,radicicol_0,DMSO_0,DMSO_0,DMSO_0,radicicol_8,radicicol_8,...,DMSO_6,DMSO_6,DMSO_6,radicicol_7,radicicol_7,radicicol_7,DMSO_7,DMSO_7,DMSO_7,id
0,00:29:10,30.0,0.279,0.269,0.313,0.247,0.230,0.182,0.159,0.244,...,0.251,0.188,0.373,0.180,0.194,0.316,0.428,0.209,0.240,0
1,00:59:10,30.0,0.277,0.260,0.301,0.243,0.230,0.181,0.157,0.238,...,0.251,0.188,0.361,0.179,0.191,0.301,0.409,0.211,0.240,1
2,01:29:10,30.2,0.268,0.255,0.292,0.241,0.229,0.181,0.157,0.234,...,0.247,0.188,0.347,0.177,0.190,0.291,0.391,0.211,0.239,2
3,01:59:10,30.1,0.263,0.251,0.285,0.238,0.226,0.184,0.157,0.230,...,0.244,0.186,0.341,0.178,0.188,0.287,0.375,0.208,0.237,3
4,02:29:10,30.0,0.263,0.249,0.286,0.236,0.228,0.185,0.157,0.226,...,0.244,0.189,0.336,0.180,0.190,0.286,0.364,0.214,0.240,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,1900-01-01 22:29:10,30.0,1.468,1.477,1.443,1.449,1.493,1.428,1.474,1.625,...,1.287,1.276,1.369,1.500,1.552,1.461,1.677,1.333,1.334,92
93,1900-01-01 22:59:10,30.1,1.475,1.484,1.450,1.450,1.492,1.428,1.482,1.627,...,1.291,1.282,1.372,1.506,1.559,1.469,1.610,1.339,1.338,93
94,1900-01-01 23:29:10,30.1,1.482,1.490,1.457,1.447,1.492,1.426,1.487,1.625,...,1.297,1.290,1.376,1.514,1.566,1.472,1.610,1.343,1.343,94
95,1900-01-01 23:59:10,30.1,1.490,1.497,1.465,1.447,1.493,1.426,1.493,1.627,...,1.300,1.295,1.379,1.523,1.575,1.481,1.614,1.347,1.348,95
96,1900-01-02 00:29:10,30.0,1.495,1.504,1.472,1.445,1.492,1.424,1.500,1.626,...,1.305,1.300,1.381,1.530,1.581,1.486,1.616,1.352,1.353,96

In [5]:
colList = raw.columns.tolist()[2:-1]
hspRoot = ['HSP' + str(num) for num in np.arange(1, 19)]
hspBase = [name for name in hspRoot for _ in range(3)]

In [6]:
long_dat = pd.wide_to_long(raw, stubnames = conditions, i = 'id', j = 'sample', sep = '_')

In [7]:
sampleDict = dict(zip(np.arange(9), samples))
numIndex = [num[1] for num in long_dat.index.tolist()]
nameIndex = [sampleDict[num] for num in numIndex]

In [13]:
sns.lineplot(x = 'id', y = 'DMSO', hue = 'sample', data = long_dat)

ValueError: Could not interpret input 'id'

In [155]:
long_dat.index.get_level_values(1)

Int64Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            ...
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
           dtype='int64', name=u'sample', length=70713)

In [162]:
long_dat['radicicol'].values

array([0.279, 0.279, 0.279, ..., 1.461, 1.461, 1.461])

In [171]:
manual_long = pd.DataFrame({'id' : long_dat.index.get_level_values(0),
              'sample' : nameIndex,
             'radicicol' : long_dat['radicicol'].values,
             'DMSO' : long_dat['DMSO'].values})

In [172]:
manual_long

        DMSO  id  radicicol sample
0      0.247   0      0.279  K298M
1      0.230   0      0.279  K298M
2      0.182   0      0.279  K298M
3      0.247   0      0.279  K298M
4      0.230   0      0.279  K298M
5      0.182   0      0.279  K298M
6      0.247   0      0.279  K298M
7      0.230   0      0.279  K298M
8      0.182   0      0.279  K298M
9      0.247   0      0.269  K298M
10     0.230   0      0.269  K298M
11     0.182   0      0.269  K298M
12     0.247   0      0.269  K298M
13     0.230   0      0.269  K298M
14     0.182   0      0.269  K298M
15     0.247   0      0.269  K298M
16     0.230   0      0.269  K298M
17     0.182   0      0.269  K298M
18     0.247   0      0.313  K298M
19     0.230   0      0.313  K298M
20     0.182   0      0.313  K298M
21     0.247   0      0.313  K298M
22     0.230   0      0.313  K298M
23     0.182   0      0.313  K298M
24     0.247   0      0.313  K298M
25     0.230   0      0.313  K298M
26     0.182   0      0.313  K298M
27     0.247   0      0.279  K298M
28     0.230   0      0.279  K298M
29     0.182   0      0.279  K298M
...      ...  ..        ...    ...
70683  1.097  96      1.461  F512P
70684  1.085  96      1.461  F512P
70685  1.099  96      1.461  F512P
70686  1.097  96      1.500  F512P
70687  1.085  96      1.500  F512P
70688  1.099  96      1.500  F512P
70689  1.097  96      1.500  F512P
70690  1.085  96      1.500  F512P
70691  1.099  96      1.500  F512P
70692  1.097  96      1.500  F512P
70693  1.085  96      1.500  F512P
70694  1.099  96      1.500  F512P
70695  1.097  96      1.626  F512P
70696  1.085  96      1.626  F512P
70697  1.099  96      1.626  F512P
70698  1.097  96      1.626  F512P
70699  1.085  96      1.626  F512P
70700  1.099  96      1.626  F512P
70701  1.097  96      1.626  F512P
70702  1.085  96      1.626  F512P
70703  1.099  96      1.626  F512P
70704  1.097  96      1.461  F512P
70705  1.085  96      1.461  F512P
70706  1.099  96      1.461  F512P
70707  1.097  96      1.461  F512P
70708  1.085  96      1.461  F512P
70709  1.099  96      1.461  F512P
70710  1.097  96      1.461  F512P
70711  1.085  96      1.461  F512P
70712  1.099  96      1.461  F512P

[70713 rows x 4 columns]